### ISSUE TITLE
Hardcoded date at bottom of each page

### ISSUE THREAD

**Issue by thingywhat** [kelvinh/org-page#101]
Heyas!

I notice that at the bottom of pages generated with org-page all say "`Copyright © 2012 - 2014`"... Like so:
![screenshot from 2015-01-19 19 57 42](https://cloud.githubusercontent.com/assets/6616922/5812096/6e38e6f4-a01f-11e4-85b6-6176a17d40e6.png)

I also notice you have a TODO near [the line that specifies this](https://github.com/kelvinh/org-page/blob/8fbfa34a61ea6a8e2c9a0ab6188c7da1b45997a4/themes/mdo/templates/footer.mustache#L66), so I know you are already aware of it... But until the TODO is complete, could this be replaced with `2015` until it is implemented? (Or, potentially add some JavaScript to change the end year...)

I actually have already forked this repo and [done the latter](https://github.com/thingywhat/org-page/commit/67fadd36e2645cd7dd1f8711f08c0368a50cd0f8?diff=split) to make it convenient if you feel like merging a pull request. You can see it in action [at the bottom of my page.](http://thingywhat.github.io/)

Thanks..!

**Comment by kelvinh** [comment]
Thanks for your great pull request, now the problem seems to be solved, and also thanks for the great avatar integration!

**Comment by thingywhat** [comment]
Neato, thanks..!

I was actually going to send the avatar stuff in another Pull Request after this one to seperate the issues, though my implementation appears to have snuck into my existing pull request. (Whoops.) Glad you like it though..!

Anyway, this issue seems solved to me, so... Closing!
