### ISSUE TITLE
When suggesting URI, replace spaces with dashes

### ISSUE THREAD

**Issue by Trevoke** [kelvinh/org-page#104]
If my blog title is `Switching to org-page` then the suggested URI should be `/blog/%y/%m/%d/Switching-to-org-page`.

**Comment by kelvinh** [comment]
Yeah, you could use `#+URI` to customize the uri:

```
#+URI:         /blog/%y/%m/%d/switching-to-org-page/
```

**Comment by kelvinh** [comment]
And, I recall that even there is no `#+URI` customization, it should be something like you suggested, so what is the generated uri for you currently?

**Comment by Trevoke** [comment]
With `M-x op/new-post` when I write the title "this is my new post", here is what gets suggested.

![screen shot 2015-01-24 at 8 28 02 am](https://cloud.githubusercontent.com/assets/67913/5887518/02365ae0-a3a3-11e4-929d-daacf718a043.png)

**Comment by kelvinh** [comment]
Oh, I see, I thought you were talking about the generation of html files, but seems it's about the new post creation, now it has been fixed.
