### ISSUE TITLE
"ASCII" ?

### ISSUE THREAD

**Issue by Trevoke** [kelvinh/org-page#105]
I want to show how an org-mode table looks before it is transformed into HTML. How can I write the org file in such a way that org-page understands I want this to look just that way?

**Comment by kelvinh** [comment]
Sorry, but could you please be more specific?

**Comment by Trevoke** [comment]
Sure.

If I create a table in the org file for the blog entry, it will be converted to HTML. And that's great. But sometimes I specifically want to SHOW how it looks in plain-text:

```
| <2015-03-05 Thu>                   | Foo bar baz  |
| <2015-03-06 Fri>--<2015-03-08 Sun> | quz bazrakux |
| <2015-03-09 Mon>                   | barnafu zbar |
| <2015-03-23 Mon>--<2015-03-24 Tue> | Quxroobarfn  |
```

How can I get it to look like that?

**Comment by Trevoke** [comment]
I figured it out.

I just have to wrap it with a 

```
#+BEGIN_EXAMPLE
#+END_EXAMPLE
```

**Comment by kelvinh** [comment]
Yeah, for org mode syntax, please refer to http://orgmode.org/org.html.

**Comment by Trevoke** [comment]
Yes, thanks :) The main thin

I think it would be helpful to know how various elements of org-mode get
converted through org-page!
