### ISSUE TITLE
Don't insert googlecode url in template mdo

### ISSUE THREAD

**Issue by tumashu** [kelvinh/org-page#112]
```
<script src="http://code.jquery.com/jquery-latest.min.js"></script>
<script src="https://google-code-prettify.googlecode.com/svn/loader/prettify.js"></script>
```

I find above two line in mdo template, which make site page  very slow in china.... you understand....

**Comment by kelvinh** [comment]
Yeah, it's because the fucking GFW, however, if we make local copies of the script files, we will have to update them manually...

Do you have any better idea?

**Comment by tumashu** [comment]
what about use a fork in github

**Comment by tumashu** [comment]
fork prettify,js to github?

**Comment by kelvinh** [comment]
It's OK, but seems still need manual effort to update...

**Comment by tumashu** [comment]
Yes, but it seemed easier and cleaner than putting prettify.js to org-page source.

Maybe we can contact the prettify.js's author, and  "huyou" he  to github, for googlecode will die.

**Comment by kelvinh** [comment]
Ha, I found a great CDN which hosts **prettify.js**: http://cdnjs.com/libraries/prettify
I tried, it loads pretty fast, could you please help test ?

I will change the CDN if it is good for you, then it would be good for all people in the fucking China.

**Comment by tumashu** [comment]
Fast too, but my college's Lan is fast.....  

At moment, I custom my own theme template and don't use any js.  for example:
    
    http://tumashu.github.com

**Comment by kelvinh** [comment]
OK, I will change to that CDN.

You site is designed very well. :-)
