### ISSUE TITLE
Add document  about build a localhost site

### ISSUE THREAD

**Issue by tumashu** [kelvinh/org-page#113]
I think we should add document which can tell the user how to build a localhost site, for example:

```
(setq op/site-domain "http://localhost/~feng")
```

**Comment by kelvinh** [comment]
It's in README:

    (setq op/site-domain "http://your.personal.site.com/")

**Comment by tumashu** [comment]
but, when I set 

```
(setq op/site-domain "http://localhost/~feng")

```

The 'blog' and 'about' url in result page seemd broken.

**Comment by kelvinh** [comment]
That must be a bug, I will check later.

**Comment by kelvinh** [comment]
I tried, seems no problems here, could you paste the broken sample here?

**Comment by tumashu** [comment]
Maybe it's my www server's problem.
