### ISSUE TITLE
[Suggese]  Add a  software site template

### ISSUE THREAD

**Issue by tumashu** [kelvinh/org-page#114]
I want use org-page to generate chinese-pyim website, but I don't like blog style.... Is it possible add
a site template which more like a software webpage?

**Comment by kelvinh** [comment]
Yeah, the page structure/style can be totally customized, however, I am not a html/css guy, so hope someone else could offer some help...

**Comment by tumashu** [comment]
Maybe we should add a README which can tell the user how to use himself theme.

**Comment by kuangdash** [comment]
@kelvinh I have applied org-page to “emacs-china.org”, and customized a theme called 'emacs_love'.
(you can see it by visiting emacs-china.org)

But since my 'git diff' and 'git patch' got some problem recently, is it convenient for you to extract the theme for a new theme of org-page? And I disabled `op/verify-comments` to support both disqus and duoshuo, hoping you can apply it to org-page……

**Comment by tumashu** [comment]
@kuangdash   Maybe we should build a emacs package which is called  `org-page-theme-lovemacs' 

I think that org-page should only include a basic theme....

**Comment by kelvinh** [comment]
@kuangdash Thanks for your effort, I really love the **table-of-contents** design.

however:

1. the copyright of this theme belongs to you, it's not proper for me to extract it and add it to org-page
2. as @tumashu said, it would be a great idea for us to create another package called `org-page-themes` to collect various themes, org-page will only include a basic theme, I will create another repository for this later.

Hope you can fix your `git` system ASAP, and it would be great that you can send a pull request for the dual commenting system integration.

**Comment by tumashu** [comment]
Ok, In my opinion we should define how to build a org-page theme package,  

let `op/theme-root-directory'  directory list,  like `load-path'?  I don't know.

The theme package names like this?
1.  org-page-themes
2.  org-page-theme-<string>

**Comment by kelvinh** [comment]
No, I will create another repo for org-page themes, and all great themes will be merged there, the theme can be easily used by set an option:

    (setq a-theme-select-variable 'a-theme-from-the-theme-package)

This is the basic idea currently I come up, if you have better ideas, please let me know.

**Comment by tumashu** [comment]
Just try, I suggest put this feature to new branch before it actually works well. by the way, 

"Don't forget the users who manager their own theme in  source dir"

**Comment by kuangdash** [comment]
@tumashu appreciate your opinion，theme should be managered in the source branch
