### ISSUE TITLE
Can't deal with org file with chinese file name?

### ISSUE THREAD

**Issue by tumashu** [kelvinh/org-page#118]
It seem that  org-files with chinese file names can't  export to html.  is it a bug?

**Comment by tumashu** [comment]
If it is hard to resolve, we should add info to doc...

**Comment by kelvinh** [comment]
No, I debugged, it is a bug in *op-git.el*, however it is too late now, I will solve this bug tomorrow...
I always named my org file with English, so I never found this bug...

**Comment by kelvinh** [comment]
After some research, this can be solved by set the `core.quotepath` to `false`:

    git config --global core.quotepath false

**Comment by tumashu** [comment]
This tips sould be included into doc.
