### ISSUE TITLE
How to ignore export a directory or a file in source?

### ISSUE THREAD

**Issue by tumashu** [kelvinh/org-page#121]
I put my theme to "/theme",  when I build website,  org-page add a nav  "Theme", 
Is it possible add a opinion to ignore a dirctory or a file, such as a variable?

**Comment by kelvinh** [comment]
Please refer to https://github.com/kelvinh/org-page/pull/106, I should have add this to README, but I forgot that...

**Comment by tumashu** [comment]
Thanks!
