### ISSUE TITLE
[question]  Is template.html auto generated by org-page?

### ISSUE THREAD

**Issue by tumashu** [kelvinh/org-page#123]
I'm confused by template.html, which seem to  have similar content with *.mustache file,  is it auto generated?  If so, I suggest put it into .gitignore

**Comment by tumashu** [comment]
If it is auto generated,  we should add some note in this file head.   for example: Auto generated by org-page, Don't edit manual ....

**Comment by kelvinh** [comment]
No, this file is used by old version org-page, now it has been deleted.
