### ISSUE TITLE
emacs 25 needed?

### ISSUE THREAD

**Issue by heikkil** [kelvinh/org-page#128]
I started my site in github a month ago. At that point I could not run op/new-repository with emacs 24.4. I upgraded to v.25 and publishing started working. 

Might be good idea to test the current code base in both emacs versions 24 and 25 and document the dependency in the documentation.

**Comment by kelvinh** [comment]
I am using Emacs 24.4, and I can run `op/new-repository` with no issue, could you please paste your error message here?

**Comment by heikkil** [comment]
Went back to 24.4 and could not reproduce the problem. Sorry. Something definitely was not working at that point but everything seems to be working now.
