### ISSUE TITLE
Cleaning the generated main index page

### ISSUE THREAD

**Issue by heikkil** [kelvinh/org-page#129]
Could you fix two small things in the function op/generate-default-index, please.

- Category names look better capitalised. Line 388 in op-export.el should be:

````cl
                          ("category" (capitalize (car cell)))
````

- Remove category 'about' from the generated index page 

The about page is already linked to from the header and it adds distracting text to the main page. Since there is no standard way in core elisp to filter a value from a list, I'd prefer to leave the task to select the cleanest way to implement filtering of value 'about' from list 'sort-alist' to you.

**Comment by kelvinh** [comment]
Yeah, now the two issues have been fixed, thanks!
