### ISSUE TITLE
Date for all entries in all index pages

### ISSUE THREAD

**Issue by heikkil** [kelvinh/org-page#130]
I am trying to make all generated lists of posts look the same. There are main index, category index and tag index. I can modify the mustache templates for the first two to get them look identical (change header levels, add date and decorations), but there is no way of adding a date into the tag index without touching code.

Could you please add post-date to the attribute list in function op/update-tags in file op-export.el. It looks to me that simply adding a sexp
````
("post-date" (plist-get attr-plist :date))
````
to line 535 might do the trick. Thanks.

**Comment by kelvinh** [comment]
Sorry for late response due to busy work previous two days, I have added the date and tested, it works now. And next time, you could just send me a pull request for this. :-)

**Comment by heikkil** [comment]
Thanks for fixing these. I can confirm they work. I'll use the pull-request way in the future once I am more confident that I understand the codebase.
