### ISSUE TITLE
org-page don't produce html file

### ISSUE THREAD

**Issue by passchaos** [kelvinh/org-page#133]
执行op/do-publication之后，source分支中的blog目录不见了，却在master分支中blog里面存放着我的org文件，没有生成html文件

**Comment by kelvinh** [comment]
Could you please provide more detailed info ?

1. How is your repo looks like, include the branches ?
2. How is the `op/do-publication` executed, what parameters did you passed in ?
3. Have those .org files occurred on `master` branch committed ?

**Comment by passchaos** [comment]
使用流程：
1、使用op/new-repository创建一个工作目录
2、使用op/new-post创建了一个org文件
3、使用op/do-publication生成html文件，除了publish-to-a-directory，其余都是y
然后就发现source分支blog目录和master分支blog目录下都没有文件

**Comment by passchaos** [comment]
我发现原因了，创建org文件之后我没有commit，能不能让op/do-publication自动commit？

**Comment by kelvinh** [comment]
Sorry, as org-page doesn't have the knowledge that which file should be committed and which should not (maybe a post is just a draft currently so it should be committed later after finished), so you should commit those posts manually, as you can decide which should commit, which should not.
