### ISSUE TITLE
为什么生成后的没有table of content？

### ISSUE THREAD

**Issue by dreamer-yzy** [kelvinh/org-page#135]

**Comment by kuangdash** [comment]
注意 #+option 选项 的 toc 选项

**Comment by kelvinh** [comment]
Yeah, as @kuangdash said, change `toc: nil` to `toc: t` in `#+OPTION` to generate toc.

**Comment by postgresqldba** [comment]
thanks all.

**Comment by postgresqldba** [comment]
thanks @kuangdash  @kelvinh
