### ISSUE TITLE
org-page 发布不了org文件

### ISSUE THREAD

**Issue by ghost** [kelvinh/org-page#138]
我在source分支建立了一个org文件，然后git add .  && git commit -m "add"，然后在emacs里，M-x op/do-publish 发布不了。
fail to commit changes on current branch of respository xxxxx。

**Comment by postgresqldba** [comment]
OS: ubuntu 14.04
Emacs : 24
org-mode : 8.x

**Comment by kuangdash** [comment]
可以按以下地址写的测试方法，测试一下：

http://emacs-china.org/blog/2015/04/15/org-page%E7%9A%84%E9%85%8D%E7%BD%AE%E4%B8%8E%E4%BD%BF%E7%94%A8/

**Comment by postgresqldba** [comment]
非常多谢你 @kuangdash  , 我的第一篇blog终于成功了.折腾了这么久.渐渐熟悉了起来.这个是我的blog, -----> http://postgresqldba.github.io/  thanks very much .

**Comment by emacsist** [comment]
不过又遇到问题，在ubuntu下，只能导出英文文件名的org，不能导出含有中文文件名的数据。在mac上，都可以，这是什么情况？locale的问题？

**Comment by kelvinh** [comment]
please refer to #118.
