### ISSUE TITLE
cannot pusblish the file which file name contains chinese .

### ISSUE THREAD

**Issue by emacsist** [kelvinh/org-page#139]
As title said. I can open and write chinese in emacs, but when I use org-page to generate static website, the file name which contains chinese cannot be published.What's problem?In my Mac Book, all thing is OK.

Env:
OS: Ubuntu 14.04.1
Emacs: 24.x
Org-mode: 8.x
locale: en_US.UTF-8

**Comment by kelvinh** [comment]
Please refer to #118, and before you submit a new issue, please search the issue list first, maybe others also meet the same problem and there is already an solution there.
