### ISSUE TITLE
Wordpress-like blog pages

### ISSUE THREAD

**Issue by shakthimaan** [kelvinh/org-page#140]
Hi,

My current blog is at http://www.shakthimaan.com/news.html.

It has a Wordpress-like list of blog posts (ten in a page, for example) with previous posts linked to "OLDER POSTS" and "NEWER". Is there a way to achieve a similar output with org-page? I really would like to move from markdown to org files for my blog posts.

Thanks!

**Comment by kelvinh** [comment]
Sorry, org-page does not support pagination, so `older posts`/`newer posts` is not supported, however, if no default index provided, org-page will generate a default index with all posts on it.
