### ISSUE TITLE
Site Preview

### ISSUE THREAD

**Issue by noctuid** [kelvinh/org-page#143]
Is there some way to preview the site before committing/pushing? It would be nice to see what the different themes look like as well as how the posts look when styled before publishing.

**Comment by kelvinh** [comment]
Sorry, no preview inside org-page, I always publish the site into nginx to preview it.

**Comment by rudolfochrist** [comment]
I use this function for previewing new posts:

~~~elisp
(defun op/do-preview ()
  (interactive)
  (let ((op/repository-org-branch (car (vc-git-branches))))
    (op/do-publication nil nil "~/Desktop/org-page-preview/preview" nil nil)))
~~~

Then I serve the files with [http-server](https://www.npmjs.com/package/http-server) locally.

**Comment by CodeFalling** [comment]
```lisp
(defun codefalling/test-org-page ()
    "test the org-page's main repository"
    (interactive)
    (op/do-publication t nil "~/codefalling.com.build")
    (httpd-serve-directory "~/codefalling.com.build")
    (browse-url (format "http://%s:%d" system-name httpd-port)))
```
Same with @rudolfochrist,got this idea from [emacs-china](http://emacs-china.org/blog/2015/04/15/org-page%E7%9A%84%E9%85%8D%E7%BD%AE%E4%B8%8E%E4%BD%BF%E7%94%A8/)

[simple-httpd](https://github.com/skeeto/emacs-web-server) required.

**Comment by rudolfochrist** [comment]
@CodeFalling I really like that EMACS-only solution. Do you think you've got the time to turn this into a pull request? I think many people would profit from it.

**Comment by CodeFalling** [comment]
@rudolfochrist @kelvinh RR ready,waiting for merging

**Comment by kelvinh** [comment]
That's really a great solution, thank you, I will verify the PR later.

**Comment by rudolfochrist** [comment]
Awesome :+1:

**Comment by noctuid** [comment]
@CodeFalling Thanks! I love the idea to use simple-httpd.
