### ISSUE TITLE
rss for each tag

### ISSUE THREAD

**Issue by shackra** [kelvinh/org-page#147]
I think generating a RSS feed for each tag is a good idea for blogs that talks about many different topics, in my blog for instance I talk a lot of Catholicism but I also include things like Free Software and Emacs in my repertoire. If some people are interested in my blog posts about emacs but don't really want to know anything about Catholicism, they should be able to subscribe to the emacs tag!

**Comment by kelvinh** [comment]
That's a good idea, but this may lead to maintain many RSS feed files, it may be not easy to display all of them on the navigation bar.

**Comment by shackra** [comment]
Well, you don't need that, is just a matter of setting the RSS feed for each tag in their respective tag page!

El miércoles 05 de agosto del 2015 a las 2335 horas, Kelvin Hu escribió:

> That's a good idea, but this may lead to maintain many RSS feed files, it may be not easy to display all of them on the navigation bar.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/kelvinh/org-page/issues/147#issuecomment-128249796

-- 
Pax et bonum.
 Jorge Araya Navarro.
 ES: Diseñador Publicitario, Programador Python y colaborador en Parabola GNU/Linux-libre
 EN: Ads Designer, Python programmer and contributor in Parabola GNU/Linux-libre
 EO: Anonco grafikisto, Pitino programalingvo programisto kai kontribuanto en Parabola GNU/Linux-libre
https://es.gravatar.com/shackra

**Comment by kelvinh** [comment]
Yeah, that makes sense, thank you, I will try to implement this when I have time.

**Comment by shackra** [comment]
Yay! Thanks!

El jueves 06 de agosto del 2015 a las 2326 horas, Kelvin Hu escribió:

> Yeah, that makes sense, thank you, I will try to implement this when I have time.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/kelvinh/org-page/issues/147#issuecomment-128602301

-- 
Pax et bonum.
 Jorge Araya Navarro.
 ES: Diseñador Publicitario, Programador Python y colaborador en Parabola GNU/Linux-libre
 EN: Ads Designer, Python programmer and contributor in Parabola GNU/Linux-libre
 EO: Anonco grafikisto, Pitino programalingvo programisto kai kontribuanto en Parabola GNU/Linux-libre
https://es.gravatar.com/shackra

**Comment by kelvinh** [comment]
Implemented.

**Comment by shackra** [comment]
YES!

El martes 18 de agosto del 2015 a las 0709 horas, Kelvin Hu escribió:

> Implemented.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/kelvinh/org-page/issues/147#issuecomment-132200306

-- 
Pax et bonum.
 Jorge Araya Navarro.
 ES: Diseñador Publicitario, Programador Python y colaborador en Parabola GNU/Linux-libre
 EN: Ads Designer, Python programmer and contributor in Parabola GNU/Linux-libre
 EO: Anonco grafikisto, Pitino programalingvo programisto kai kontribuanto en Parabola GNU/Linux-libre
https://es.gravatar.com/shackra

**Comment by kelvinh** [comment]
Will be available in melpa later, there is delay for melpa to sync the newest change from GitHub.

**Comment by kelvinh** [comment]
By the way, the feature is disabled by default, you should set the following variable to enable it:

    (setq op/tag-rss t)

**Comment by shackra** [comment]
Sure, thank you!
