### ISSUE TITLE
Add custom index.htmls

### ISSUE THREAD

**Issue by fxfactorial** [kelvinh/org-page#153]
On master:

I thought that just adding a root directory with a index.html that that would be enough to create a separate link, (yes I did add the link to the root index.html.), but it isn't and I get a 404. 

What do I need to do to create custom paths/index.htmls? My use case is I have generated code documentation that I want to code on my github pages as well.

**Comment by kelvinh** [comment]
Sorry that I didn't understand you well, do you want to customize index pages for categories? then you need to copy the original theme `mdo` and customize the template `category-index.mustache`, hope that helps.

**Comment by fxfactorial** [comment]
I have right now this Top level link called OCamldocs
http://hyegar.com
but it is 404ing right now. When you click on it i want it go to a page with say n number of link, where each link is a sub folder which contains an index.html.

**Comment by kelvinh** [comment]
http://hyegar.com/OCamlDocs/index.html, the page is OK, seems you need to make the cases right, otherwise the page cannot be found...

for sub folder contains an index.html, you can customize the `URI` option in org file:

    #+URI:         /OCamlDocs/sub1/sub2

**Comment by fxfactorial** [comment]
Ah! That's where it was, I couldn't find it. 

Where do I add that #+URI  ? On source's index.org?

**Comment by kelvinh** [comment]
Yeah, in your org source file, the `#+URI` option will decide where the generate html goes.

**Comment by fxfactorial** [comment]
Okay but I mean this is just a collection of html files, they are already generated. Its not like I have a org file to generate these.

**Comment by kelvinh** [comment]
Oh, that is beyond org-page's ability, I think you can manually commit these html files to master branch, and then write an index.org file contains the links to these pages, and then convert it into an index.html with org-page.

**Comment by fxfactorial** [comment]
I've been trying this but with little success. Is there really no easy way to do this, how much effort would it take to add this ability.
