### ISSUE TITLE
Add LinkedIn link to navigation

### ISSUE THREAD

**Issue by ldenman** [kelvinh/org-page#159]
It would be useful to have an link to a linkedin profile in the nav. thoughts?

**Comment by kelvinh** [comment]
In my opinion, linkedin is not so important that we need a special link in the nav bar, instead, you can add a link on index/about page, especially the about page, on that page you can add various links, to your twitter, facebook, linkedin, etc.

**Comment by ldenman** [comment]
Cool, that makes sense to me. Cheers!
