### ISSUE TITLE
Wishlist  + bug fixes + clarification

### ISSUE THREAD

**Issue by fxfactorial** [kelvinh/org-page#165]
1) What is the difference between tags and keywords? Looks like the same thing
2) Can you implement or expose more options to control the CSS? At least for code blocks. I'm having to do an extra commit on master each time I want to publish to fix the CSS
3) It doesn't seem to be that case that the RSS feed actually respects tags, I want to expose my RSS feed to an aggregator but only want the coding related posts to be there. 

Thanks again for this super easy to use and useful tool, much appreciated.

**Comment by kelvinh** [comment]
1) Keywords are used for search engines, tags are used to aggregate posts, they are basically same but you can add more keywords to improve the searching for your site
2) You can copy the default theme somewhere, and customize it, and set the variable `op/theme` and `op/theme-root-directory` to make org-page use your customized version
3) Sorry, but currently this is not supported..

**Comment by fxfactorial** [comment]
Okay thank you. #3 sounds like a nice PR elisp opportunity :)
