### ISSUE TITLE
应该提示一下git命令的执行结果不能包含中文字符！

### ISSUE THREAD

**Issue by Yihulee** [kelvinh/org-page#166]
我在Ubuntu kylin里面折腾org-page,怎么折腾怎么不对，老是发布不了东西，后来看了一下代码，原来代码里通过与git命令的返回结果的比对来判断成功与否，本来说问题不大的，但是坑爹的是，kylin系统里面是中文的git，是的，你没听错，这导致了，程序对结果的判断老是出错，后来我删掉了中文，换成了英文，问题解决了！

**Comment by kelvinh** [comment]
因为在实现org-page的时候，就没有考虑过中文系统的问题，所以这个确实是个疏忽，你可以把你的错误和相关的git输出贴在这里，后续会加强git使用这一块的逻辑。

**Comment by kelvinh** [comment]
PR #176 has fixed this issue, closing.
