### ISSUE TITLE
Org-page not handling emphasis correctly

### ISSUE THREAD

**Issue by brittAnderson** [kelvinh/org-page#173]
In orgmode if I write this: /text/ and export to HTML I should get this _text_ , but instead with `op/do-publication-and-preview-site` I get this /_text_/. The word is properly italicized, but the slashes are not removed.

**Comment by kelvinh** [comment]
The slashes in html are generated by CSS styles, not by html text. See [this](https://github.com/kelvinh/org-page/blob/master/themes/mdo/resources/css/main.css#L86).

**Comment by brittAnderson** [comment]
Okay. I will edit the CSS for the "/" and "=" of the code delimiters and I you can close the issue, but why do you want to retain the orgmode mark-up in the html? For an org-mode based system, don't you want the final product looking more like the org-mode export to HTML does?

**Comment by kelvinh** [comment]
It's just a theme, it looks cool for me to emulate org mode elements in html pages, if you feel it's weird, you could customize it and make it your style. :-p
