### ISSUE TITLE
[no match]

### ISSUE THREAD

**Issue by AaronFeldman** [kelvinh/org-page#174]
Tried to install and use as advised, but am getting [no match] when M-x op/publish in emacs.  Not sure why.

**Comment by CodyReichert** [comment]
Have you tried running `M-x` `package-refresh-contents` first? Sounds like it might be trying to get an old version from Melpa.

**Comment by AaronFeldman** [comment]
​Ok.  Am trying that now, although it is seeming to hang on "Contacting
host: melpa.org:80"

Thank you for the quick response.  I'm new(ish) to emacs and certainly to
org-page.  Hopefully this is the start of a long fruitful relationship with
both.  Are you the developer?​

**Comment by AaronFeldman** [comment]
Looks like I have a bug in my Melpa.  I'll fix that first.  Thanks.

**Comment by AaronFeldman** [comment]
I think that I managed to update the package store updated (because it
asked me if I wanted to update, although when  I updated I noticed it
seemed to be pulling updates from Elpa)

Still seems to be the same error.  I am trying to html publish a plain .org
file that I have on my system.

**Comment by CodyReichert** [comment]
Hey @AaronFeldman - I'm not sure where my comment went!

At any rate, I'm not the developer, just thought it might be a problem with the package version. Good you got it updated but I'll let someone else chime in with some more troubleshooting steps, I'm at the end of my knowledget with org-page :)

**Comment by kelvinh** [comment]
Thanks @CodyReichert ! Hi @AaronFeldman, the publication command should be `op/do-publication`, not `op/publish`, have you tried that?

**Comment by AaronFeldman** [comment]
Will try it and report back.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Kelvin HuSent: Monday, February 29, 2016 9:45 PMTo: kelvinh/org-pageReply To: kelvinh/org-pageCc: AaronFeldmanSubject: Re: [org-page] [no match] (#174)Thanks @CodyReichert ! Hi @AaronFeldman, the publication command should be op/do-publication, not op/publish, have you tried that?

—Reply to this email directly or view it on GitHub.

**Comment by AaronFeldman** [comment]
Same problem when I use op/do-publication

**Comment by AaronFeldman** [comment]
(require 'org-page)
  (setq op/repository-directory "media/dadsnewfiles/Aaron-Org-Mode")   ;; the repository location

**Comment by kelvinh** [comment]
Please paste output in ***Messages*** buffer here when you executing the command.

**Comment by AaronFeldman** [comment]
Unfortunately attempting M-x op/do-publication does not output anything into the Messages buffer.  In that regard it is strange, [no match] which disappears quickly is the only indication of a failed command.

**Comment by kelvinh** [comment]
Seems it's because the command cannot be found, probably your org-page is not loaded. you could execute `(require 'org-page)` in **Scratch** buffer with `C-x C-e` and see what happens, and then try `op/do-publication` again.

**Comment by AaronFeldman** [comment]
Thanks @kelvinh I tried evaluating it in the Scratch buffer as you said and it loaded.  I have to figure out the rest, but now I think it is doable.

**Comment by kelvinh** [comment]
Great to see it finally works. :-)
