### ISSUE TITLE
"new post" function should take you to the correct branch

### ISSUE THREAD

**Issue by Trevoke** [kelvinh/org-page#178]
I think every single time I've tried to write a blog entry (maybe 10 or so .. I don't write all that often), I trustfully choose the "new post" function, write my new post, publish it, then realize I didn't publish it at all.

**Comment by kelvinh** [comment]
You are right, we should change to `source` branch first.

**Comment by kelvinh** [comment]
fixed, but may still need some time to sync the fix to melpa repo.
