### ISSUE TITLE
Generate content on main index page

### ISSUE THREAD

**Issue by Linuus** [kelvinh/org-page#180]
Hi!

I'm trying to create my blog with org-page but have som questions.

1. The main index file is static? Can I replace it with a list of my posts (like the archive page) instead? (Like this http://nick.balestra.ch)
2. Can I preview the site before committing? It seems I have to stage and commit locally before previewing, is that correct?

Thanks

**Comment by kelvinh** [comment]
1. if you do not provider an index.org, org-page will generate one index page for you, basically it's a list of posts.
2. yes, you can, there is a function doing this job: `op/do-publication-and-preview-site`.

**Comment by Linuus** [comment]
1. Oh, nice. I'll try that!
2. Yes, I ran that function but it didn't update anything unless I did a commit first.

- Edit files
- Run `op/do-publication-and-preview-site` => No updates in preview
- Commit changes
- Run `op/do-publication-and-preview-site` => Changes are displayed

Is that the intended behavior?

**Comment by Linuus** [comment]
Another update. So the issue with content not being previewed was that it must be added to git first. So when you create a new blog post it must be staged before you can preview it. After that you can just add away and run the preview command. Cool!

**Comment by Trevoke** [comment]
This is one of those things that should probably be added to the Readme :)

**Comment by sandric** [comment]
Looks like its not working now - if I remove index.org file I get in messages buffer `Opening input file: No such file or directory, /Users/sandric/.emacs.d/sandric.github.io/index.org`

**Comment by kelvinh** [comment]
try removing and then committing the change?
