### ISSUE TITLE
Add images to posts

### ISSUE THREAD

**Issue by Linuus** [kelvinh/org-page#182]
Hi!

I'm trying to add images to my org blog posts and I can only make it work with web urls so far, not local files.

Should I put my images somewhere special?
Is it even possible?

**Comment by smaximov** [comment]
Place a file (i.e., `img.png`) in the directory where your blog post is stored, then you add it to the post using following link: `file:img.png`. Example layout:

```
/blog
├── img.png
└── post.org
```

…and somewhere in `post.org`:

``` 
...

#+caption:Optional caption
[[file:img.png]]

...
```

**Comment by Linuus** [comment]
@smaximov Cool! Thanks!
