### ISSUE TITLE
No example org source files in https://github.com/kelvinh/kelvinh.github.com?

### ISSUE THREAD

**Issue by WangLeshan** [kelvinh/org-page#189]
In the README file, you said that 
>  The html files and org source files are located at https://github.com/kelvinh/kelvinh.github.com. If you want to give org-page a try, you could take them as an example.
but I can not find the org source files.

Searching for ` filetype:org  site:github.com/kelvinh` one can find many org files in your github site, but searching for `filetype:org github.com/kelvinh/kelvinh.github.com` one gets no results.

Could you show me the path of the org source files or upload some example source files to github? Thank you.

**Comment by smaximov** [comment]
Hello, @WangLeshan. Org source files are located in the [source](https://github.com/kelvinh/kelvinh.github.com/tree/source) branch.

**Comment by WangLeshan** [comment]
@smaximov
Thank you very much!
