### ISSUE TITLE
Cannot create a new post

### ISSUE THREAD

**Issue by dilzeem** [kelvinh/org-page#197]
Hi, 

I am using Spacemacs (0.105.21) and Emacs (24.5.1). I installed org-page from Melpa.

I can successfully create a new repository, and I have the git files intialized, readme, index.org and about.org created. I also ensure that I am on the source branch when I am create a new post I get the following error.

```
git-error: GIT Error: "Error running command: c:/Program Files/Git/cmd/git.exe --no-pager checkout source
error: pathspec 'source' did not match any file(s) known to git.
```
I am not sure what the error is to be honest? This is what have I put as my init file. 

```
  (require 'org-page)
  (setq op/repository-directory "~/org/blog")   ;; the repository location
  (setq op/site-domain "http://dilzeem.github.io")         ;; your domain
  (setq op/personal-github-link "https://github.com/dilzeem")
  (setq op/site-main-title "The One True Blog")
  (setq op/site-sub-title "Emacs, Programming, and Arch Linux")
  (setq op/personal-disqus-shortname "dilzeem")    ;; your disqus commenting system
```

**Comment by kelvinh** [comment]
The error says there is no "source", if you are sure "source" branch exists, then run the command in a cmd shell, see if there is the same error.

**Comment by dilzeem** [comment]
Thanks for your response. I solved the error. It was a typo on my end. Thank you for an excellent package.

**Comment by kelvinh** [comment]
Glad you solved the problem! :)
