### ISSUE TITLE
Weather a datail work flow should be add to README file?

### ISSUE THREAD

**Issue by zhcosin** [kelvinh/org-page#200]
Hi, I was trying publish my org-mode file to github pages by org-page, I found I must commit my org file first befor execute op/do-publish, otherwise the html file is not generated, but I has not found this information in README and quick-start.org, so I suggest add this work flow into README or quick-start.org.
The right workflow is:  op/new-post --> save org file --> commit --> op/do-publish

Additional remarks: I was confused for a long time at this problem, I thought it will be commited automatically when execute op/do-publish. :-).

**Comment by kelvinh** [comment]
added a note to README
