### ISSUE TITLE
Maybe the URI of a new post use the filename instead of the title is better?

### ISSUE THREAD

**Issue by zhcosin** [kelvinh/org-page#201]
Because my post name is English and the title is Chinese, but I want the URI is English...

**Comment by zhcosin** [comment]
The benefit use the filename instead of the title is some character not applicable for url such as blank space may be contained in title.

**Comment by kelvinh** [comment]
Your could have your own uri-generator, have a look at my config:
https://github.com/kelvinh/dotfiles/blob/master/emacs/spacemacs#L356

**Comment by zhcosin** [comment]
Thanks.
