### ISSUE TITLE
Wrong type argument: listp

### ISSUE THREAD

**Issue by zhcosin** [kelvinh/org-page#203]
I found a problem rencent, When I export a org file into html(not the publish in org-page), a error bellow has been occur:
> Wrong type argument: listp, #("zhcosin@163.com" 0 24 (:parent (#0)))
and I found a directory named org-20161102 under .emacs.d/elpa, if I remove this directory, the problem went away.
So whether org-page will download its dependency org-mode?

**Comment by kelvinh** [comment]
No, the dependencies are managed by your own configuration, if you don't have a package manager, you need to manage the dependencies manually; if you use `package.el`, it will download the dependencies automatically (after properly configured).

**Comment by zhcosin** [comment]
Thanks for your reply.
