### ISSUE TITLE
How to add a small preview of posts in the index page?

### ISSUE THREAD

**Issue by nasseralkmim** [kelvinh/org-page#208]
I tried without success to change the default index template so the post list include a small preview of them.

Do you have any guidance on how to accomplish that?

If it's possible I would like to show an image associated with the post, to increase visual interest in the content.

**Comment by kelvinh** [comment]
Add `#+THUMBNAIL` option in the posts, and customize the "index.mustache", place `{{post-thumb}}` at the place you want, good luck!
