### ISSUE TITLE
wrong-type-argument lisp #("About" 0 5 (:parent (#1)))

### ISSUE THREAD

**Issue by samrayleung** [kelvinh/org-page#209]
i follow this blog [使用org-page搭建个人博客](http://google-ebook.com/blog/2015/12/24/%E4%BD%BF%E7%94%A8org-page%E6%90%AD%E5%BB%BA%E4%B8%AA%E4%BA%BA%E5%8D%9A%E5%AE%A2/) and your guide to configure my blog,but it couldn't work
my emacs version:`25.1`
my org-mode version:`9.0.5`
my org-page version:`20170206.1845 `
my configuration:
```
(use-package org-page
  :ensure t
  :config (progn
	    (setq op/repository-directory "~/Documents/Blog" ;;local repo location
		  ;; op/repository-org-branch "source" ;;org-file branch
		  ;; op/repository-html-branch "master" ;;html-file(published) brance
		  op/personal-github-link "https://github.com/samrayleung" ;;github link
		  op/site-domain "myserver"
		  op/site-main-title "从Hello World开始"
		  op/theme 'mdo) ;; theme
	    )
  )

```
My Step:
1. `M-x op/new-post`
2. finish writing
3. git add new blog (under source branch) and commit it (use magit)
4. in *scratch* buffer ,run `(op/do-publication t nil nil t)`
Then,fail to publish , debugger  show as below
Backtrace
```
Debugger entered--Lisp error: (wrong-type-argument listp #("About" 0 5 (:parent (#1))))
  org-element-set-contents(#("About" 0 5 (:parent (#0))))
* apply(org-element-set-contents #("About" 0 5 (:parent (#0))) nil)
  #[257 "\211\305\306\307#\310\311\211:\204
  op/do-publication(t nil nil t)
  eval((op/do-publication t nil nil t) nil)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
```
and i have checked  all the issues [#68](https://github.com/kelvinh/org-page/issues/68),[#152](https://github.com/kelvinh/org-page/issues/152) #184 ,and i have tried to remove my `elpa` ,and can't works
i need help -_-!

**Comment by kelvinh** [comment]
Is The repo at https://github.com/samrayleung/samrayleung.github.io? I tried, without any error, do you have any difference between your local repo with this one?

**Comment by kelvinh** [comment]
If the error still exists, try cloning a working org-page blog repo (like mine), and then do the publication on it to see if the error exists, if it still exists, try remove all your org-* packages and re-install them; if not, it must be something wrong with your repo, you may need to check if your repo matches org-page's requirements.

BTW, you could use `op/new-repository` to create a repo which matches org-page's requirements.

**Comment by samrayleung** [comment]
After i remove all `org-*` packages and reinstall again ,i get it work.Thank you Kelvln,you do a good job,org-page is awesome.But i think if you are free ,could you improve the document? IMO,if the awesome tool comes with detailed document,it is best.we all will appreciate it.thanks again
