### ISSUE TITLE
I cannot get generated html posts

### ISSUE THREAD

**Issue by Txellenne** [kelvinh/org-page#210]
Hi there. 
Really nice job from I can see as demo but what if I (only) wanted to create/publish to a local blog (so, doing not committing or pushing to git (or, eventually, doing this afterwards, manually)). Also, as offered, as it reads on https://github.com/kelvinh/org-page/blame/master/README.org#L85 . Why (after setq op/repository-directory as instructed) when running either  `Mx op/do-publication` [RET, y, n,n,n] or [n,RET, y/n, n,n,] *or* `op/do-publication-and-preview-site` it only putouts:
 `GIT Error: "Repository not initialized"`. I'd appreciate any help.

**Comment by kelvinh** [comment]
The location referenced by `op/repository-directory` must be a valid git repo, did you initialize it? If not, try `op/new-repository` to create a valid org-page git repo. If the repo is valid, double check if the value of `op/repository-directory` is correct.

**Comment by Txellenne** [comment]
mmm.. the reason I put this eventuality is the case of having not one but several repositories (being all of them managed from the same pc) (so dealing with the fact of either setting *multiple remote repo's,* every each with a `identity ssh-key`, as suggested e.g. **[here](http://stackoverflow.com/questions/7927750/specify-an-ssh-key-for-git-push-for-a-given-domainas)**  or using *a kind of git-admin*, or a global `alias` as documented e.g. **[here](https://noamlewis.wordpress.com/2013/01/24/git-admin-an-alias-for-running-git-commands-as-a-privileged-ssh-identity/)**. So in the worst scenery I wanted to be able to get the `master` dir fed & fit with the html files produced by `org-page` & afterwards, making the process of git-commiting/pushing to e.g github repository at my own. Thanks.

**Comment by kelvinh** [comment]
Glad you solved it!

**Comment by Txellenne** [comment]
not solved but thanks, anyway.
