### ISSUE TITLE
Cannot change date format in generated category indexes

### ISSUE THREAD

**Issue by drtutut** [kelvinh/org-page#213]
Hello,

I noticed that it is not possible to change the format of the dates in the category indexes.
I introduced a new customizable variable which allows to specify a formating function for this date (by default, this function is just the identity function). This function is then applied during the generation of index pages. Would you be interested by a pull request ?

Eric

**Comment by kelvinh** [comment]
Yes, PRs are always welcome!

**Comment by drtutut** [comment]
Done ;o) I forked and submitted a PR.
