### ISSUE TITLE
Org-page does not ignore the themes folder

### ISSUE THREAD

**Issue by localredhead** [kelvinh/org-page#217]
<img width="869" alt="screen shot 2017-05-21 at 1 16 26 am" src="https://cloud.githubusercontent.com/assets/152448/26286511/3d748364-3e1c-11e7-9f0f-f123b399552c.png">

I've found that I need to make adjustments to the theme I want to use so I have a themes folder in the root of my project.  The themes folder is not being ignored even though it is specified as a default category to ignore.

in the index.mustache file `{{#categories}}` is returning "themes" but it should not.

**Comment by kelvinh** [comment]
Did you set `op/category-ignore-list`?

**Comment by localredhead** [comment]
Yes :(

**Comment by kelvinh** [comment]
The newest commit should have fixed this problem.
