### ISSUE TITLE
Symbol's function definition is void:seq-take

### ISSUE THREAD

**Issue by ccsheller** [kelvinh/org-page#220]
I use the spacemacs.I wrote a layer for org-page.Use it all right on windows.
I suddenly found the result was not correct on ubuntu.I run it again,spacemacs says:

> Symbol's function definition is void:seq-take

So,I add (require 'seq) in op-export.el and it seams right.
but spacemacs says:

> can't find the file seq

i search 'seq' in .emacs.d,the package is in the dir.

**Comment by ccsheller** [comment]
No useful information on google.
spacemacs community : the issue was closed.
flycheck community : the issue was closed.

They mentioned the update packages.
This is useless.

@NicolasPetton says:seq is built in emacs 25.

so i reinstall the emacs 24.5 to 25.2.

fixed this issue.

**Comment by NicolasPetton** [comment]
The package should add a dependency to `seq`, which will then be pulled from ELPA on Emacs 24.5.
