### ISSUE TITLE
op/render-content: Invalid function: (org-html-fontify-code (code lang) (when code (org-html-encode-plain-text code)))

### ISSUE THREAD

**Issue by shackra** [kelvinh/org-page#98]
I'm trying to change the CSS used on my blog for my own with Bootstrap. I wanted to generate my blog to a directory to see the changes in my web browser, however, when I tried to generate the pages I got this error:

```
Publish all org files? (y or n) y
Publish to a directory? (to original repo if not) (y or n) y
Read post.mustache from file
op/render-content: Invalid function: (org-html-fontify-code (code lang) (when code (org-html-encode-plain-text code)))
```

So far, I just have modified the `header.mustache` file removing all `link` tags and putting my own:

```
    <link rel="stylesheet" href="/media/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="/media/css/keys.css" type="text/css">
```

org-page is a great project, hope it gets some more love!

**Comment by shackra** [comment]
adding back `<link rel="stylesheet" href="/media/css/prettify.css" type="text/css">` doesn't solve this issue (just wanted to note that)

**Comment by kelvinh** [comment]
Could you please check which version of org-mode did you use? `org-html-fontify-code` is a function from org-mode, it is provided in org-mode v8.0 and later, I am not sure it is provided in previous version or not.

**Comment by shackra** [comment]
Sure! I'm using `Org-mode version 8.2.10 (8.2.10-29-g89a0ac-elpa @ /home/jorge/.emacs.d/elpa/org-20141229/)`

**Comment by kelvinh** [comment]
That's weird, could you please retry the generation after evaluating `(require 'ox-html)`? Seems the module contains that function is not loaded.

**Comment by shackra** [comment]
Well, didn't work:

```
ox-html
Publish all org files? (y or n) n
Publish to a directory? (to original repo if not) (y or n) y
Read post.mustache from file
op/render-content: Invalid function: (org-html-fontify-code (code lang) (when code (org-html-encode-plain-text code)))
```

Kelvin Hu writes:

> That's weird, could you please retry the generation after evaluating `(require 'ox-html)`? Seems the module contains that function is not loaded.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/kelvinh/org-page/issues/98#issuecomment-68668908

-- 
Pax et bonum.
Jorge Araya Navarro.
ES: Diseñador Publicitario, Programador Python y colaborador en Parabola GNU/Linux-libre
EN: Ads Designer, Python programmer and contributor Parabola GNU/Linux-libre
EO: Anonco grafikisto, Pitino programalingvo programisto kai kontribuanto en Parabola GNU/Linux-libre
https://es.gravatar.com/shackra

**Comment by kelvinh** [comment]
OK, please post your Emacs' version, org version, and your Emacs' configuration here, I will try to reproduce this issue.

**Comment by shackra** [comment]
Good:

Emacs version: GNU Emacs 24.4.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.14.3) of 2014-10-21 on
bitzer.hoetzel.info

org-version: Org-mode version 8.2.10 (8.2.10-29-g89a0ac-elpa @ /home/jorge/.emacs.d/elpa/org-20141229/)

Emacs configuration: here! just clone my repo https://github.com/shackra/.emacs.d all the packages I have
installed here will be installed automatically if you don't have them installed!

Kelvin Hu writes:

> OK, please post your Emacs' version, org version, and your Emacs' configuration here, I will try to reproduce this issue.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/kelvinh/org-page/issues/98#issuecomment-68856750

-- 
Pax et bonum.
Jorge Araya Navarro.
ES: Diseñador Publicitario, Programador Python y colaborador en Parabola GNU/Linux-libre
EN: Ads Designer, Python programmer and contributor Parabola GNU/Linux-libre
EO: Anonco grafikisto, Pitino programalingvo programisto kai kontribuanto en Parabola GNU/Linux-libre
https://es.gravatar.com/shackra

**Comment by shackra** [comment]
anything new on this?

**Comment by kelvinh** [comment]
I tried with your Emacs configuration, only modified the following code block in you **emacs-init.org**:

        (setf op/repository-directory "~/devel/kelvinh.github.com" ;;<== modified to point it to my own repo
              op/site-domain "http://elblog.deshackra.com/"
              op/site-main-title "El blog de Shackra"
              op/site-sub-title "«No seas tan abierto de mente o tu cerebro se caerá» ~G.K. Chesterton"
              op/personal-github-link "https://github.com/shackra"
              ;; commented out the following two lines
              ;;op/theme-root-directory (expand-file-name "org-page-themes" user-emacs-directory)
              ;;op/theme 'shc
        )

Then, I tried with `op/do-publication`, it works without any error. Is your local Emacs configuration the same as it on GitHub?

**Comment by shackra** [comment]
Yes, I have changed few things but nothing related to those two lines. I'll try that.

under this circumstances, how could I choose other theme than the default one?

**Comment by kelvinh** [comment]
No, I commented out the two lines just because the theme and theme directory do not exist on my machine, you can use the customized theme directory and themes if they do exist there.

**Comment by shackra** [comment]
Ok, that's weird because it is the actual configuration. I'll try again and be back to you soon!

**Comment by shackra** [comment]
Well, the issue is gone! and I didn't change anything in my configuration!

I must say, however, that I'm actually using a new laptop and that org-page was fresh-installed automatically by my configuration, this may have some influence over this bug.

**Comment by kelvinh** [comment]
Glad to see that it is solved finally. :-)
